//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.10.10 at 11:33:58 PM EDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://samplewkspc/sample-web-service", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package samplewkspc.sample_web_service;
